CREATE DATABASE QUANLYGIAOVU
USE QUANLYGIAOVU
CREATE TABLE KHOA
(
	MAKHOA	varchar(4) PRIMARY KEY,
	TENKHOA	varchar(40),
	NGTLAP	smalldatetime,
	TRGKHOA	char(4)
);

CREATE TABLE MONHOC
(
	MAMH	varchar(10) PRIMARY KEY,
	TENMH	varchar(40),
	TCLT	tinyint,
	TCTH	tinyint,
	MAKHOA	varchar(4) REFERENCES KHOA(MAKHOA), 
	);

CREATE TABLE DIEUKIEN
(
	MAMH		varchar(10) REFERENCES MONHOC(MAMH),
	MAMH_TRUOC	varchar(10)  REFERENCES MONHOC(MAMH),
	PRIMARY KEY(MAMH, MAMH_TRUOC),
);

CREATE TABLE GIAOVIEN
(
	MAGV		char(4) PRIMARY KEY,
	HOTEN		varchar(40),
	HOCVI		varchar(10),
	HOCHAM		varchar(10),
	GIOITINH	varchar(3),
	NGSINH		smalldatetime,
	NGVL		smalldatetime,
	HESO		numeric(4,2),
	MUCLUONG	money,
	MAKHOA		varchar(4) REFERENCES KHOA(MAKHOA),
);


CREATE TABLE HOCVIEN
(
	MAHV		char(5) PRIMARY KEY,
	HO		varchar(40),
	TEN		varchar(10),
	NGSINH		smalldatetime,
	GIOITINH	varchar(3),
	NOISINH		varchar(40),
	MALOP		char(3),
);


CREATE TABLE LOP
(
	MALOP	char(3) PRIMARY KEY,
	TENLOP	varchar(40),
	TRGLOP	char(5) REFERENCES HOCVIEN(MAHV),
	SISO	tinyint,
	MAGVCN	char(4) REFERENCES GIAOVIEN(MAGV),
	
);

CREATE TABLE GIANGDAY
(
	MALOP	char(3) PRIMARY KEY,
	MAMH	varchar(10) REFERENCES MONHOC(MAMH),
	MAGV	char(4),
	HOCKY	tinyint,
	NAM	smallint,
	TUNGAY	smalldatetime,
	DENNGAY	smalldatetime,
);

CREATE TABLE KETQUATHI
(
	MAHV	char(5) REFERENCES HOCVIEN(MAHV),
	MAMH	varchar(10) REFERENCES MONHOC(MAMH),
	LANTHI	tinyint,
	NGTHI	smalldatetime,
	DIEM	numeric(4,2),
	KQUA	varchar(10),
);
ALTER TABLE HOCVIEN ADD CONSTRAINT M CHECK(GIOITINH IN ('NAM','NU'))

ALTER TABLE KETQUATHI ALTER COLUMN DIEM NUMERIC(4,2)
ALTER TABLE KETQUATHI ADD CONSTRAINT K CHECK(DIEM BETWEEN 0 AND 10)

ALTER TABLE KETQUATHI ADD CONSTRAINT L CHECK(((KQUA='DAT')AND(DIEM BETWEEN 5 AND 10)) OR((KQUA='KHONG DAT')AND(DIEM <5)))

ALTER TABLE KETQUATHI ADD CONSTRAINT LAN CHECK(LANTHI<=3)

ALTER TABLE GIANGDAY ADD CONSTRAINT HK CHECK (HOCKY BETWEEN 1 AND 3)

ALTER TABLE GIAOVIEN ADD CONSTRAINT HVI CHECK(HOCVI IN('CN','KS','THS','TS','PTS')) 



