CREATE DATABASE QUANLYBANHANG
USE QUANLYBANHANG
CREATE TABLE KHACHHANG
(
 MAKH  char(4) PRIMARY KEY,
 HOTEN varchar(40),
 DCHI  varchar(50),
 SODT  varchar(20),
 NGSINH smalldatetime,
 NGDK  smalldatetime,
 DOANHSO money
);
CREATE TABLE NHANVIEN
(
 MANV  char(4)PRIMARY KEY,
 HOTEN varchar(40),
 SODT  varchar(20),
 NGVL  smalldatetime
);
CREATE TABLE SANPHAM
(
 MASP  char(4)PRIMARY KEY,
 TENSP varchar(40),
 DVT  varchar(20),
 NUOCSX varchar(40),
 GIA  money
);
CREATE TABLE HOADON
(
 SOHD  int PRIMARY KEY,
 NGHD  smalldatetime,
 MAKH  char(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
 MANV  char(4) FOREIGN KEY REFERENCES NHANVIEN(MANV),
 TRIGIA money
);
CREATE TABLE CTHD
(
 SOHD  int FOREIGN KEY REFERENCES HOADON(SOHD),
 MASP  char(4) FOREIGN KEY REFERENCES SANPHAM(MASP),
 SL  int,
 CONSTRAINT PK_CTHD PRIMARY KEY (SOHD,MASP)
);
ALTER TABLE SANPHAM  ADD GHICHU VARCHAR(20)
ALTER TABLE KHACHHANG  ADD LOAIKH TINYINT
ALTER TABLE SANPHAM  ALTER COLUMN GHICHU VARCHAR(100)
ALTER TABLE SANPHAM  DROP COLUMN GHICHU
ALTER TABLE KHACHHANG  ALTER COLUMN LOAIKH VARCHAR(20)
ALTER TABLE SANPHAM  ADD CONSTRAINT SANPHAM_DVT CHECK (DVT = 'cay' OR DVT = 'hop' OR DVT = 'cai' OR DVT = 'quyen' OR DVT = 'chuc')
ALTER TABLE SANPHAM ADD CONSTRAINT SANPHAM_GIA CHECK(GIA > 500)
ALTER TABLE CTHD ADD CHECK(SL >=1)
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGDK CHECK (NGDK>NGSINH)







